---
name: POE-Component-Client-MPD
version: v0.9.3
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: a full-blown mpd client library
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Audio::MPD::Common: v0.1.4
  Carp: 0
  Class::Accessor::Fast: 0
  Exporter: 0
  FindBin: 0
  POE: 0
  POE::Component::Client::TCP: 0
  Readonly: 0
  Test::More: 0
  perl: 5.010
requires:
  Audio::MPD::Common: v0.1.4
  Carp: 0
  Class::Accessor::Fast: 0
  Exporter: 0
  POE: 0
  POE::Component::Client::TCP: 0
  Readonly: 0
  perl: 5.010
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  Module::Build: 0.35
provides:
  POE::Component::Client::MPD:
    file: lib/POE/Component/Client/MPD.pm
    version: v0.9.3
  POE::Component::Client::MPD::Collection:
    file: lib/POE/Component/Client/MPD/Collection.pm
  POE::Component::Client::MPD::Commands:
    file: lib/POE/Component/Client/MPD/Commands.pm
  POE::Component::Client::MPD::Connection:
    file: lib/POE/Component/Client/MPD/Connection.pm
  POE::Component::Client::MPD::Message:
    file: lib/POE/Component/Client/MPD/Message.pm
  POE::Component::Client::MPD::Playlist:
    file: lib/POE/Component/Client/MPD/Playlist.pm
  POE::Component::Client::MPD::Test:
    file: lib/POE/Component/Client/MPD/Test.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
