---
abstract: 'full-blown poe-aware mpd client library'
author:
  - 'Jerome Quelin'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::More: '0.88'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POE-Component-Client-MPD
provides:
  POE::Component::Client::MPD:
    file: lib/POE/Component/Client/MPD.pm
    version: '2.000'
  POE::Component::Client::MPD::Collection:
    file: lib/POE/Component/Client/MPD/Collection.pm
    version: '2.000'
  POE::Component::Client::MPD::Commands:
    file: lib/POE/Component/Client/MPD/Commands.pm
    version: '2.000'
  POE::Component::Client::MPD::Connection:
    file: lib/POE/Component/Client/MPD/Connection.pm
    version: '2.000'
  POE::Component::Client::MPD::Message:
    file: lib/POE/Component/Client/MPD/Message.pm
    version: '2.000'
  POE::Component::Client::MPD::Playlist:
    file: lib/POE/Component/Client/MPD/Playlist.pm
    version: '2.000'
  POE::Component::Client::MPD::Test:
    file: lib/POE/Component/Client/MPD/Test.pm
    version: '2.000'
  POE::Component::Client::MPD::Types:
    file: lib/POE/Component/Client/MPD/Types.pm
    version: '2.000'
requires:
  Audio::MPD::Common::Item: '0'
  Audio::MPD::Common::Stats: '0'
  Audio::MPD::Common::Status: '0'
  Carp: '0'
  List::AllUtils: '0'
  Moose: '0.92'
  Moose::Util::TypeConstraints: '0'
  MooseX::Has::Sugar: '0'
  MooseX::POE: '0'
  MooseX::SemiAffordanceAccessor: '0'
  MooseX::Types::Moose: '0'
  POE: '0'
  POE::Component::Client::TCP: '0'
  Readonly: '0'
  Sub::Exporter: '0'
  Test::Corpus::Audio::MPD: '1.120990'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  MailingList: http://groups.google.com/group/audio-mpd
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=POE-Component-Client-MPD
  homepage: http://search.cpan.org/dist/POE-Component-Client-MPD/
  repository: git://github.com/jquelin/poe-component-client-mpd.git
version: '2.000'
x_Dist_Zilla:
  perl:
    version: '5.020000'
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.001'
          version_by_branch: '0'
          version_regexp: (?^:^v(.+)$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::JQUELIN/Git::NextVersion'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::JQUELIN/GatherDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::JQUELIN/Test::Compile'
      version: '2.042'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::JQUELIN/PodCoverageTests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::JQUELIN/PodSyntaxTests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::JQUELIN/ReportVersions::Tiny'
      version: '1.10'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::JQUELIN/PruneCruft'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::JQUELIN/PruneFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::JQUELIN/ManifestSkip'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::JQUELIN/AutoPrereqs'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::JQUELIN/ExtraTests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::JQUELIN/NextRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::JQUELIN/PkgVersion'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: EVENTS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: MPD_CTRL
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: MPD_OUTPUT
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: MPD_INFO
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: MPD_SETTINGS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: MPD_PLAYBACK
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: COLL_SONG
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: COLL_WHOLE
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: COLL_PICK
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: COLL_RELATIONS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: PLAY_INFO
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: PLAY_ADDRM
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: PLAY_ORDER
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: PLAY_MGMT
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.006'
      name: '@Author::JQUELIN/PodWeaver'
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Author::JQUELIN/Prepender'
      version: '1.112280'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::JQUELIN/ExecDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::JQUELIN/ShareDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Author::JQUELIN/Bugtracker'
      version: '1.111080'
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Author::JQUELIN/Homepage'
      version: '1.101420'
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::JQUELIN/Repository'
      version: '0.20'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::JQUELIN/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.019'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@Author::JQUELIN/MetaProvides::Package'
      version: '2.000001'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::JQUELIN/MetaConfig'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::HelpWanted
      name: '@Author::JQUELIN/HelpWanted'
      version: 0.3.1
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::JQUELIN/License'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Covenant
      name: '@Author::JQUELIN/Covenant'
      version: 0.1.0
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::JQUELIN/MetaYAML'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::JQUELIN/MetaJSON'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Author::JQUELIN/ModuleBuild'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::JQUELIN/Readme'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::JQUELIN/ReadmeAnyFromPod'
      version: '0.141120'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::JQUELIN/Manifest'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Author::JQUELIN/CheckChangeLog'
      version: '0.01'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::JQUELIN/TestRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
            - README.mkdn
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::JQUELIN/Git::Check'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
            - README.mkdn
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::JQUELIN/Git::Commit'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v2.000
          tag_format: v%v
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::JQUELIN/Git::Tag'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::JQUELIN/Git::Push'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::JQUELIN/UploadToCPAN'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::JQUELIN/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.019'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.019'
x_author_pledge:
  version: 1
