---
name: POE-Component-Client-MPD
version: 0.8.0
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: a full-blown mpd client library
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Audio::MPD::Common: 0
  Class::Accessor: 0
  List::MoreUtils: 0
  POE: 0
  Readonly: 0
  perl: 5.8.0
build_requires:
  Test::More: 0
provides:
  POE::Component::Client::MPD:
    file: lib/POE/Component/Client/MPD.pm
    version: 0.8.0
  POE::Component::Client::MPD::Collection:
    file: lib/POE/Component/Client/MPD/Collection.pm
  POE::Component::Client::MPD::Commands:
    file: lib/POE/Component/Client/MPD/Commands.pm
  POE::Component::Client::MPD::Connection:
    file: lib/POE/Component/Client/MPD/Connection.pm
  POE::Component::Client::MPD::Message:
    file: lib/POE/Component/Client/MPD/Message.pm
  POE::Component::Client::MPD::Playlist:
    file: lib/POE/Component/Client/MPD/Playlist.pm
  POE::Component::Client::MPD::Test:
    file: lib/POE/Component/Client/MPD/Test.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
